### ISSUE TITLE
验证码看不清楚

### ISSUE THREAD

**Issue by zhaojunliing** [Biulink/ShadowsocksTutorials#9]
你好，首先感谢提供这个好的服务。
验证码真的分辨不出来，能不能提供二维码。
虽然理解使用验证码为了防止机器自动识别连接，但是验证码真的看出来。

**Comment by Biulink** [comment]
谢谢你的建议，我会考虑使用更友好的方式来展示密码。

**Comment by Biulink** [comment]
已经关闭服务。

**Comment by bobyangchina** [comment]
为何?到期了?遗憾啊。。。
